Update get-dump.yml

diff --git a/.github/workflows/get-dump.yml b/.github/workflows/get-dump.yml
--- a/.github/workflows/get-dump.yml
+++ b/.github/workflows/get-dump.yml
@@ -45,18 +45,24 @@ jobs:
       # Step 4: Execute wkhtmltopdf commands with delay and error reporting
       - name: Execute wkhtmltopdf commands with delay and error handling
         run: |
+          cp /dev/null success_download.txt
           i=0
           while read line; do
             # Enhanced wkhtmltopdf command with error handling
             wget -q -O - $line | grep -oE "question\s[0-9]+" > ./tmpr
             if [ $? == 0 ] && [ "$(cat ./tmpr|head -n 1  | tr  ' ' '-')" != "" ];then
-              fname=$(cat ./tmpr|head -n 1  | tr  ' ' '-').pdf ; 
+              fname=$(cat ./tmpr|head -n 1  | tr  ' ' '-').pdf ;
               echo "file name : $fname ------>"
               cp /dev/null ./report
-              if ! bash -c "(echo _______ For line $((++i)) _____; echo 'CMD : wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line $fname' ; wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line $fname 2>&1 | tee -a ./report)"; then
-                echo "Error occurred: Rerun Line : $((++i))" >> ./report
+              if [ -f "./q/$fname" ];then
+                if ! bash -c "(echo _______ For line $((++i)) _____; echo 'CMD : wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line $fname' ; wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line $fname 2>&1 | tee -a ./report)"; then
+                  echo "Error occurred: Rerun Line : $((++i))" >> ./report
+                fi
+                sleep $(shuf -i 3-8 -n 1)
+                if [ -f "./$fname" ];then
+                  echo $line | grep -oE 'view/[0-9]+' | tr -d 'view/' >> success_download.txt
+                fi
               fi
-              sleep $(shuf -i 3-8 -n 1)
             else 
               echo $line >> ./reprocess ;
               continue;
@@ -64,7 +70,10 @@ jobs:
           done < ./source.txt
           grep -i error ./report >> run_report.txt || true
           mv *.pdf q/ || true
-          
+
+          if ! [ -s success_download.txt ];then
+            for i in $(cat success_download.txt); do sed -i -e "/"${i}"/d" ./source.txt ; done
+          fi
       # - name: Set output variables
       #   id: vars
       #   run: echo "fcount=$(wc -l source.txt)" >> $GITHUB_OUTPUT
@@ -83,7 +92,7 @@ jobs:
       - name: Commit and push changes
         if: always()
         run: |
-          rm -f wkhtml* report ./tmpr || true
+          rm -f wkhtml* report ./tmpr success_download.txt || true
           ls -ltr
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
